-- 交易日历（时间锚点）
CREATE TABLE IF NOT EXISTS trade_cal (
    exchange       TEXT NOT NULL,
    cal_date       TEXT NOT NULL,
    is_open        INTEGER NOT NULL,
    pretrade_date  TEXT,
    PRIMARY KEY (exchange, cal_date)
);

-- 拉取日志（驱动回填判断）
CREATE TABLE IF NOT EXISTS pull_log (
    table_name  TEXT NOT NULL,
    date_val    TEXT NOT NULL,
    ok          INTEGER NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_try    TEXT DEFAULT NULL,
    PRIMARY KEY (table_name, date_val)
);

-- ETF基本信息
CREATE TABLE IF NOT EXISTS "etf_basic" (
    ts_code TEXT,
    csname TEXT,
    extname TEXT,
    cname TEXT,
    index_code TEXT,
    index_name TEXT,
    setup_date TEXT,
    list_date TEXT,
    list_status TEXT,
    exchange TEXT,
    mgr_name TEXT,
    custod_name TEXT,
    mgt_fee REAL,
    etf_type TEXT,
    PRIMARY KEY (ts_code)
);

-- ETF复权因子
CREATE TABLE IF NOT EXISTS "fund_adj" (
    ts_code TEXT,
    trade_date TEXT,
    adj_factor REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 可转债技术面因子(专业版)
CREATE TABLE IF NOT EXISTS "cb_factor_pro" (
    ts_code TEXT,
    trade_date TEXT,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    pre_close REAL,
    change REAL,
    pct_change REAL,
    vol REAL,
    amount REAL,
    asi_bfq REAL,
    asit_bfq REAL,
    atr_bfq REAL,
    bbi_bfq REAL,
    bias1_bfq REAL,
    bias2_bfq REAL,
    bias3_bfq REAL,
    boll_lower_bfq REAL,
    boll_mid_bfq REAL,
    boll_upper_bfq REAL,
    brar_ar_bfq REAL,
    brar_br_bfq REAL,
    cci_bfq REAL,
    cr_bfq REAL,
    dfma_dif_bfq REAL,
    dfma_difma_bfq REAL,
    dmi_adx_bfq REAL,
    dmi_adxr_bfq REAL,
    dmi_mdi_bfq REAL,
    dmi_pdi_bfq REAL,
    downdays REAL,
    updays REAL,
    dpo_bfq REAL,
    madpo_bfq REAL,
    ema_bfq_10 REAL,
    ema_bfq_20 REAL,
    ema_bfq_250 REAL,
    ema_bfq_30 REAL,
    ema_bfq_5 REAL,
    ema_bfq_60 REAL,
    ema_bfq_90 REAL,
    emv_bfq REAL,
    maemv_bfq REAL,
    expma_12_bfq REAL,
    expma_50_bfq REAL,
    kdj_bfq REAL,
    kdj_d_bfq REAL,
    kdj_k_bfq REAL,
    ktn_down_bfq REAL,
    ktn_mid_bfq REAL,
    ktn_upper_bfq REAL,
    lowdays REAL,
    topdays REAL,
    ma_bfq_10 REAL,
    ma_bfq_20 REAL,
    ma_bfq_250 REAL,
    ma_bfq_30 REAL,
    ma_bfq_5 REAL,
    ma_bfq_60 REAL,
    ma_bfq_90 REAL,
    macd_bfq REAL,
    macd_dea_bfq REAL,
    macd_dif_bfq REAL,
    mass_bfq REAL,
    ma_mass_bfq REAL,
    mfi_bfq REAL,
    mtm_bfq REAL,
    mtmma_bfq REAL,
    obv_bfq REAL,
    psy_bfq REAL,
    psyma_bfq REAL,
    roc_bfq REAL,
    maroc_bfq REAL,
    rsi_bfq_12 REAL,
    rsi_bfq_24 REAL,
    rsi_bfq_6 REAL,
    taq_down_bfq REAL,
    taq_mid_bfq REAL,
    taq_up_bfq REAL,
    trix_bfq REAL,
    trma_bfq REAL,
    vr_bfq REAL,
    wr_bfq REAL,
    wr1_bfq REAL,
    xsii_td1_bfq REAL,
    xsii_td2_bfq REAL,
    xsii_td3_bfq REAL,
    xsii_td4_bfq REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 可转债基础信息
CREATE TABLE IF NOT EXISTS "cb_basic" (
    ts_code TEXT,
    bond_full_name TEXT,
    bond_short_name TEXT,
    cb_code TEXT,
    cb_type TEXT,
    stk_code TEXT,
    stk_short_name TEXT,
    maturity REAL,
    par REAL,
    issue_price REAL,
    issue_size REAL,
    remain_size REAL,
    value_date TEXT,
    maturity_date TEXT,
    rate_type TEXT,
    coupon_rate REAL,
    add_rate REAL,
    pay_per_year INTEGER,
    list_date TEXT,
    delist_date TEXT,
    exchange TEXT,
    conv_start_date TEXT,
    conv_end_date TEXT,
    conv_stop_date TEXT,
    first_conv_price REAL,
    conv_price REAL,
    rate_clause TEXT,
    put_clause TEXT,
    maturity_call_price TEXT,
    maturity_put_price TEXT,
    call_clause TEXT,
    reset_clause TEXT,
    conv_clause TEXT,
    guarantor TEXT,
    guarantee_type TEXT,
    issue_rating TEXT,
    newest_rating TEXT,
    rating_comp TEXT,
    PRIMARY KEY (ts_code)
);

-- 基金技术面因子(专业版)
CREATE TABLE IF NOT EXISTS "fund_factor_pro" (
    ts_code TEXT,
    trade_date TEXT,
    trade_date_doris TEXT,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    pre_close REAL,
    change REAL,
    pct_change REAL,
    vol REAL,
    amount REAL,
    asi_bfq REAL,
    asit_bfq REAL,
    atr_bfq REAL,
    bbi_bfq REAL,
    bias1_bfq REAL,
    bias2_bfq REAL,
    bias3_bfq REAL,
    boll_lower_bfq REAL,
    boll_mid_bfq REAL,
    boll_upper_bfq REAL,
    brar_ar_bfq REAL,
    brar_br_bfq REAL,
    cci_bfq REAL,
    cr_bfq REAL,
    dfma_dif_bfq REAL,
    dfma_difma_bfq REAL,
    dmi_adx_bfq REAL,
    dmi_adxr_bfq REAL,
    dmi_mdi_bfq REAL,
    dmi_pdi_bfq REAL,
    downdays REAL,
    updays REAL,
    dpo_bfq REAL,
    madpo_bfq REAL,
    ema_bfq_10 REAL,
    ema_bfq_20 REAL,
    ema_bfq_250 REAL,
    ema_bfq_30 REAL,
    ema_bfq_5 REAL,
    ema_bfq_60 REAL,
    ema_bfq_90 REAL,
    emv_bfq REAL,
    maemv_bfq REAL,
    expma_12_bfq REAL,
    expma_50_bfq REAL,
    kdj_bfq REAL,
    kdj_d_bfq REAL,
    kdj_k_bfq REAL,
    ktn_down_bfq REAL,
    ktn_mid_bfq REAL,
    ktn_upper_bfq REAL,
    lowdays REAL,
    topdays REAL,
    ma_bfq_10 REAL,
    ma_bfq_20 REAL,
    ma_bfq_250 REAL,
    ma_bfq_30 REAL,
    ma_bfq_5 REAL,
    ma_bfq_60 REAL,
    ma_bfq_90 REAL,
    macd_bfq REAL,
    macd_dea_bfq REAL,
    macd_dif_bfq REAL,
    mass_bfq REAL,
    ma_mass_bfq REAL,
    mfi_bfq REAL,
    mtm_bfq REAL,
    mtmma_bfq REAL,
    obv_bfq REAL,
    psy_bfq REAL,
    psyma_bfq REAL,
    roc_bfq REAL,
    maroc_bfq REAL,
    rsi_bfq_12 REAL,
    rsi_bfq_24 REAL,
    rsi_bfq_6 REAL,
    taq_down_bfq REAL,
    taq_mid_bfq REAL,
    taq_up_bfq REAL,
    trix_bfq REAL,
    trma_bfq REAL,
    vr_bfq REAL,
    wr_bfq REAL,
    wr1_bfq REAL,
    xsii_td1_bfq REAL,
    xsii_td2_bfq REAL,
    xsii_td3_bfq REAL,
    xsii_td4_bfq REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 广州民间借贷利率
CREATE TABLE IF NOT EXISTS "gz_index" (
    date TEXT,
    d10_rate REAL,
    m1_rate REAL,
    m3_rate REAL,
    m6_rate REAL,
    m12_rate REAL,
    long_rate REAL,
    PRIMARY KEY (date)
);

-- 沪深市场每日交易统计
CREATE TABLE IF NOT EXISTS "daily_info" (
    trade_date TEXT,
    ts_code TEXT,
    ts_name TEXT,
    com_count INTEGER,
    total_share REAL,
    float_share REAL,
    total_mv REAL,
    float_mv REAL,
    amount REAL,
    vol REAL,
    trans_count INTEGER,
    pe REAL,
    tr REAL,
    exchange TEXT,
    PRIMARY KEY (ts_code, trade_date)
);

-- 申万行业分类
CREATE TABLE IF NOT EXISTS "index_classify" (
    index_code TEXT,
    industry_name TEXT,
    parent_code TEXT,
    level TEXT,
    industry_code TEXT,
    is_pub TEXT,
    src TEXT,
    PRIMARY KEY (index_code)
);

-- 深圳市场每日交易情况
CREATE TABLE IF NOT EXISTS "sz_daily_info" (
    trade_date TEXT,
    ts_code TEXT,
    count INTEGER,
    amount REAL,
    vol TEXT,
    total_share REAL,
    total_mv REAL,
    float_share REAL,
    float_mv REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 大盘指数每日指标
CREATE TABLE IF NOT EXISTS "index_dailybasic" (
    ts_code TEXT,
    trade_date TEXT,
    total_mv REAL,
    float_mv REAL,
    total_share REAL,
    float_share REAL,
    free_share REAL,
    turnover_rate REAL,
    turnover_rate_f REAL,
    pe REAL,
    pe_ttm REAL,
    pb REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 指数成分和权重
CREATE TABLE IF NOT EXISTS "index_weight" (
    index_code TEXT,
    con_code TEXT,
    trade_date TEXT,
    weight REAL,
    PRIMARY KEY (index_code, con_code, trade_date)
);

-- 中信行业成分
CREATE TABLE IF NOT EXISTS "ci_index_member" (
    l1_code TEXT,
    l1_name TEXT,
    l2_code TEXT,
    l2_name TEXT,
    l3_code TEXT,
    l3_name TEXT,
    ts_code TEXT,
    name TEXT,
    in_date TEXT,
    out_date TEXT,
    is_new TEXT,
    PRIMARY KEY (ts_code)
);

-- 指数技术面因子(专业版)
CREATE TABLE IF NOT EXISTS "idx_factor_pro" (
    ts_code TEXT,
    trade_date TEXT,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    pre_close REAL,
    change REAL,
    pct_change REAL,
    vol REAL,
    amount REAL,
    asi_bfq REAL,
    asit_bfq REAL,
    atr_bfq REAL,
    bbi_bfq REAL,
    bias1_bfq REAL,
    bias2_bfq REAL,
    bias3_bfq REAL,
    boll_lower_bfq REAL,
    boll_mid_bfq REAL,
    boll_upper_bfq REAL,
    brar_ar_bfq REAL,
    brar_br_bfq REAL,
    cci_bfq REAL,
    cr_bfq REAL,
    dfma_dif_bfq REAL,
    dfma_difma_bfq REAL,
    dmi_adx_bfq REAL,
    dmi_adxr_bfq REAL,
    dmi_mdi_bfq REAL,
    dmi_pdi_bfq REAL,
    downdays REAL,
    updays REAL,
    dpo_bfq REAL,
    madpo_bfq REAL,
    ema_bfq_10 REAL,
    ema_bfq_20 REAL,
    ema_bfq_250 REAL,
    ema_bfq_30 REAL,
    ema_bfq_5 REAL,
    ema_bfq_60 REAL,
    ema_bfq_90 REAL,
    emv_bfq REAL,
    maemv_bfq REAL,
    expma_12_bfq REAL,
    expma_50_bfq REAL,
    kdj_bfq REAL,
    kdj_d_bfq REAL,
    kdj_k_bfq REAL,
    ktn_down_bfq REAL,
    ktn_mid_bfq REAL,
    ktn_upper_bfq REAL,
    lowdays REAL,
    topdays REAL,
    ma_bfq_10 REAL,
    ma_bfq_20 REAL,
    ma_bfq_250 REAL,
    ma_bfq_30 REAL,
    ma_bfq_5 REAL,
    ma_bfq_60 REAL,
    ma_bfq_90 REAL,
    macd_bfq REAL,
    macd_dea_bfq REAL,
    macd_dif_bfq REAL,
    mass_bfq REAL,
    ma_mass_bfq REAL,
    mfi_bfq REAL,
    mtm_bfq REAL,
    mtmma_bfq REAL,
    obv_bfq REAL,
    psy_bfq REAL,
    psyma_bfq REAL,
    roc_bfq REAL,
    maroc_bfq REAL,
    rsi_bfq_12 REAL,
    rsi_bfq_24 REAL,
    rsi_bfq_6 REAL,
    taq_down_bfq REAL,
    taq_mid_bfq REAL,
    taq_up_bfq REAL,
    trix_bfq REAL,
    trma_bfq REAL,
    vr_bfq REAL,
    wr_bfq REAL,
    wr1_bfq REAL,
    xsii_td1_bfq REAL,
    xsii_td2_bfq REAL,
    xsii_td3_bfq REAL,
    xsii_td4_bfq REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 申万行业成分(分级)
CREATE TABLE IF NOT EXISTS "index_member_all" (
    l1_code TEXT,
    l1_name TEXT,
    l2_code TEXT,
    l2_name TEXT,
    l3_code TEXT,
    l3_name TEXT,
    ts_code TEXT,
    name TEXT,
    in_date TEXT,
    out_date TEXT,
    is_new TEXT,
    PRIMARY KEY (ts_code)
);

-- 申万行业指数日行情
CREATE TABLE IF NOT EXISTS "sw_daily" (
    ts_code TEXT,
    trade_date TEXT,
    name TEXT,
    open REAL,
    low REAL,
    high REAL,
    close REAL,
    change REAL,
    pct_change REAL,
    vol REAL,
    amount REAL,
    pe REAL,
    pb REAL,
    float_mv REAL,
    total_mv REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 指数基本信息
CREATE TABLE IF NOT EXISTS "index_basic" (
    ts_code TEXT,
    name TEXT,
    fullname TEXT,
    market TEXT,
    publisher TEXT,
    index_type TEXT,
    category TEXT,
    base_date TEXT,
    base_point REAL,
    list_date TEXT,
    weight_rule TEXT,
    "desc" TEXT,
    exp_date TEXT,
    PRIMARY KEY (ts_code)
);

-- 融资融券交易明细
CREATE TABLE IF NOT EXISTS "margin_detail" (
    trade_date TEXT,
    ts_code TEXT,
    name TEXT,
    rzye REAL,
    rqye REAL,
    rzmre REAL,
    rqyl REAL,
    rzche REAL,
    rqchl REAL,
    rqmcl REAL,
    rzrqye REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 融资融券交易汇总
CREATE TABLE IF NOT EXISTS "margin" (
    trade_date TEXT,
    exchange_id TEXT,
    rzye REAL,
    rzmre REAL,
    rzche REAL,
    rqye REAL,
    rqmcl REAL,
    rzrqye REAL,
    rqyl REAL,
    PRIMARY KEY (exchange_id, trade_date)
);

-- 股票回购
CREATE TABLE IF NOT EXISTS "repurchase" (
    ts_code TEXT,
    ann_date TEXT,
    end_date TEXT,
    proc TEXT,
    exp_date TEXT,
    vol REAL,
    amount REAL,
    high_limit REAL,
    low_limit REAL,
    PRIMARY KEY (ts_code, ann_date)
);

-- 大宗交易
CREATE TABLE IF NOT EXISTS "block_trade" (
    ts_code TEXT,
    trade_date TEXT,
    price REAL,
    vol REAL,
    amount REAL,
    buyer TEXT,
    seller TEXT,
    PRIMARY KEY (ts_code, trade_date)
);

-- 股东人数
CREATE TABLE IF NOT EXISTS "stk_holdernumber" (
    ts_code TEXT,
    ann_date TEXT,
    end_date TEXT,
    holder_num INTEGER,
    PRIMARY KEY (ts_code, ann_date)
);

-- 股东增减持
CREATE TABLE IF NOT EXISTS "stk_holdertrade" (
    ts_code TEXT,
    ann_date TEXT,
    holder_name TEXT,
    holder_type TEXT,
    in_de TEXT,
    change_vol REAL,
    change_ratio REAL,
    after_share REAL,
    after_ratio REAL,
    avg_price REAL,
    total_share REAL,
    begin_date TEXT,
    close_date TEXT,
    PRIMARY KEY (ts_code, ann_date)
);

-- 股权质押明细数据
CREATE TABLE IF NOT EXISTS "pledge_detail" (
    ts_code TEXT,
    ann_date TEXT,
    holder_name TEXT,
    pledge_amount REAL,
    start_date TEXT,
    end_date TEXT,
    is_release TEXT,
    release_date TEXT,
    pledgor TEXT,
    holding_amount REAL,
    pledged_amount REAL,
    p_total_ratio REAL,
    h_total_ratio REAL,
    is_buyback TEXT,
    PRIMARY KEY (ts_code, ann_date)
);

-- 沪深港通股票列表
CREATE TABLE IF NOT EXISTS "stock_hsgt" (
    ts_code TEXT,
    trade_date TEXT,
    type TEXT,
    name TEXT,
    type_name TEXT,
    PRIMARY KEY (ts_code, trade_date)
);

-- ST股票列表
CREATE TABLE IF NOT EXISTS "stock_st" (
    ts_code TEXT,
    name TEXT,
    trade_date TEXT,
    type TEXT,
    type_name TEXT,
    PRIMARY KEY (ts_code, trade_date)
);

-- 交易日历
CREATE TABLE IF NOT EXISTS "trade_cal" (
    exchange TEXT,
    cal_date TEXT,
    is_open TEXT,
    pretrade_date TEXT
);

-- 股票列表
CREATE TABLE IF NOT EXISTS "stock_basic" (
    ts_code TEXT,
    symbol TEXT,
    name TEXT,
    area TEXT,
    industry TEXT,
    fullname TEXT,
    enname TEXT,
    cnspell TEXT,
    market TEXT,
    exchange TEXT,
    curr_type TEXT,
    list_status TEXT,
    list_date TEXT,
    delist_date TEXT,
    is_hs TEXT,
    act_name TEXT,
    act_ent_type TEXT,
    PRIMARY KEY (ts_code)
);

-- 股票历史列表
CREATE TABLE IF NOT EXISTS "bak_basic" (
    trade_date TEXT,
    ts_code TEXT,
    name TEXT,
    industry TEXT,
    area TEXT,
    pe REAL,
    float_share REAL,
    total_share REAL,
    total_assets REAL,
    liquid_assets REAL,
    fixed_assets REAL,
    reserved REAL,
    reserved_pershare REAL,
    eps REAL,
    bvps REAL,
    pb REAL,
    list_date TEXT,
    undp REAL,
    per_undp REAL,
    rev_yoy REAL,
    profit_yoy REAL,
    gpr REAL,
    npr REAL,
    holder_num INTEGER,
    PRIMARY KEY (ts_code, trade_date)
);

-- 涨跌停和炸板数据
CREATE TABLE IF NOT EXISTS "limit_list_d" (
    trade_date TEXT,
    ts_code TEXT,
    industry TEXT,
    name TEXT,
    close REAL,
    pct_chg REAL,
    amount REAL,
    limit_amount REAL,
    float_mv REAL,
    total_mv REAL,
    turnover_ratio REAL,
    fd_amount REAL,
    first_time TEXT,
    last_time TEXT,
    open_times INTEGER,
    up_stat TEXT,
    limit_times INTEGER,
    "limit" TEXT,
    PRIMARY KEY (ts_code, trade_date)
);

-- 市场游资最全名录
CREATE TABLE IF NOT EXISTS "hm_list" (
    name TEXT,
    "desc" TEXT,
    orgs TEXT
);

-- 榜单数据(开盘啦)
CREATE TABLE IF NOT EXISTS "kpl_list" (
    ts_code TEXT,
    name TEXT,
    trade_date TEXT,
    lu_time TEXT,
    ld_time TEXT,
    open_time TEXT,
    last_time TEXT,
    lu_desc TEXT,
    tag TEXT,
    theme TEXT,
    net_change REAL,
    bid_amount REAL,
    status TEXT,
    bid_change REAL,
    bid_turnover REAL,
    lu_bid_vol REAL,
    pct_chg REAL,
    bid_pct_chg REAL,
    rt_pct_chg REAL,
    limit_order REAL,
    amount REAL,
    turnover_rate REAL,
    free_float REAL,
    lu_limit_order REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 龙虎榜机构交易单
CREATE TABLE IF NOT EXISTS "top_inst" (
    trade_date TEXT,
    ts_code TEXT,
    exalter TEXT,
    side TEXT,
    buy REAL,
    buy_rate REAL,
    sell REAL,
    sell_rate REAL,
    net_buy REAL,
    reason TEXT,
    PRIMARY KEY (ts_code, trade_date)
);

-- 题材成分(开盘啦)
CREATE TABLE IF NOT EXISTS "kpl_concept_cons" (
    ts_code TEXT,
    name TEXT,
    con_name TEXT,
    con_code TEXT,
    trade_date TEXT,
    "desc" TEXT,
    hot_num INTEGER,
    PRIMARY KEY (ts_code, trade_date)
);

-- 龙虎榜每日统计单
CREATE TABLE IF NOT EXISTS "top_list" (
    trade_date TEXT,
    ts_code TEXT,
    name TEXT,
    close REAL,
    pct_change REAL,
    turnover_rate REAL,
    amount REAL,
    l_sell REAL,
    l_buy REAL,
    l_amount REAL,
    net_amount REAL,
    net_rate REAL,
    amount_rate REAL,
    float_values REAL,
    reason TEXT,
    PRIMARY KEY (ts_code, trade_date)
);

-- 每日筹码及胜率
CREATE TABLE IF NOT EXISTS "cyq_perf" (
    ts_code TEXT,
    trade_date TEXT,
    his_low REAL,
    his_high REAL,
    cost_5pct REAL,
    cost_15pct REAL,
    cost_50pct REAL,
    cost_85pct REAL,
    cost_95pct REAL,
    weight_avg REAL,
    winner_rate REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 股票技术面因子(专业版)
CREATE TABLE IF NOT EXISTS "stk_factor_pro" (
    ts_code TEXT,
    trade_date TEXT,
    open REAL,
    open_hfq REAL,
    open_qfq REAL,
    high REAL,
    high_hfq REAL,
    high_qfq REAL,
    low REAL,
    low_hfq REAL,
    low_qfq REAL,
    close REAL,
    close_hfq REAL,
    close_qfq REAL,
    pre_close REAL,
    change REAL,
    pct_chg REAL,
    vol REAL,
    amount REAL,
    turnover_rate REAL,
    turnover_rate_f REAL,
    volume_ratio REAL,
    pe REAL,
    pe_ttm REAL,
    pb REAL,
    ps REAL,
    ps_ttm REAL,
    dv_ratio REAL,
    dv_ttm REAL,
    total_share REAL,
    float_share REAL,
    free_share REAL,
    total_mv REAL,
    circ_mv REAL,
    adj_factor REAL,
    ema_bfq_5 REAL,
    ema_hfq_5 REAL,
    ema_qfq_5 REAL,
    ema_bfq_10 REAL,
    ema_hfq_10 REAL,
    ema_qfq_10 REAL,
    ema_bfq_20 REAL,
    ema_hfq_20 REAL,
    ema_qfq_20 REAL,
    ema_bfq_30 REAL,
    ema_hfq_30 REAL,
    ema_qfq_30 REAL,
    ema_bfq_60 REAL,
    ema_hfq_60 REAL,
    ema_qfq_60 REAL,
    ema_bfq_90 REAL,
    ema_hfq_90 REAL,
    ema_qfq_90 REAL,
    ema_bfq_250 REAL,
    ema_hfq_250 REAL,
    ema_qfq_250 REAL,
    ma_bfq_5 REAL,
    ma_hfq_5 REAL,
    ma_qfq_5 REAL,
    ma_bfq_10 REAL,
    ma_hfq_10 REAL,
    ma_qfq_10 REAL,
    ma_bfq_20 REAL,
    ma_hfq_20 REAL,
    ma_qfq_20 REAL,
    ma_bfq_30 REAL,
    ma_hfq_30 REAL,
    ma_qfq_30 REAL,
    ma_bfq_60 REAL,
    ma_hfq_60 REAL,
    ma_qfq_60 REAL,
    ma_bfq_90 REAL,
    ma_hfq_90 REAL,
    ma_qfq_90 REAL,
    ma_bfq_250 REAL,
    ma_hfq_250 REAL,
    ma_qfq_250 REAL,
    rsi_bfq_6 REAL,
    rsi_hfq_6 REAL,
    rsi_qfq_6 REAL,
    rsi_bfq_12 REAL,
    rsi_hfq_12 REAL,
    rsi_qfq_12 REAL,
    rsi_bfq_24 REAL,
    rsi_hfq_24 REAL,
    rsi_qfq_24 REAL,
    asi_bfq REAL,
    asi_hfq REAL,
    asi_qfq REAL,
    asit_bfq REAL,
    asit_hfq REAL,
    asit_qfq REAL,
    atr_bfq REAL,
    atr_hfq REAL,
    atr_qfq REAL,
    bbi_bfq REAL,
    bbi_hfq REAL,
    bbi_qfq REAL,
    bias1_bfq REAL,
    bias1_hfq REAL,
    bias1_qfq REAL,
    bias2_bfq REAL,
    bias2_hfq REAL,
    bias2_qfq REAL,
    bias3_bfq REAL,
    bias3_hfq REAL,
    bias3_qfq REAL,
    boll_lower_bfq REAL,
    boll_lower_hfq REAL,
    boll_lower_qfq REAL,
    boll_mid_bfq REAL,
    boll_mid_hfq REAL,
    boll_mid_qfq REAL,
    boll_upper_bfq REAL,
    boll_upper_hfq REAL,
    boll_upper_qfq REAL,
    brar_ar_bfq REAL,
    brar_ar_hfq REAL,
    brar_ar_qfq REAL,
    brar_br_bfq REAL,
    brar_br_hfq REAL,
    brar_br_qfq REAL,
    cci_bfq REAL,
    cci_hfq REAL,
    cci_qfq REAL,
    cr_bfq REAL,
    cr_hfq REAL,
    cr_qfq REAL,
    dfma_dif_bfq REAL,
    dfma_dif_hfq REAL,
    dfma_dif_qfq REAL,
    dfma_difma_bfq REAL,
    dfma_difma_hfq REAL,
    dfma_difma_qfq REAL,
    dmi_adx_bfq REAL,
    dmi_adx_hfq REAL,
    dmi_adx_qfq REAL,
    dmi_adxr_bfq REAL,
    dmi_adxr_hfq REAL,
    dmi_adxr_qfq REAL,
    dmi_mdi_bfq REAL,
    dmi_mdi_hfq REAL,
    dmi_mdi_qfq REAL,
    dmi_pdi_bfq REAL,
    dmi_pdi_hfq REAL,
    dmi_pdi_qfq REAL,
    downdays_bfq REAL,
    downdays_hfq REAL,
    downdays_qfq REAL,
    updays_bfq REAL,
    updays_hfq REAL,
    updays_qfq REAL,
    dpo_bfq REAL,
    dpo_hfq REAL,
    dpo_qfq REAL,
    madpo_bfq REAL,
    madpo_hfq REAL,
    madpo_qfq REAL,
    emv_bfq REAL,
    emv_hfq REAL,
    emv_qfq REAL,
    maemv_bfq REAL,
    maemv_hfq REAL,
    maemv_qfq REAL,
    expma_12_bfq REAL,
    expma_12_hfq REAL,
    expma_12_qfq REAL,
    expma_50_bfq REAL,
    expma_50_hfq REAL,
    expma_50_qfq REAL,
    kdj_bfq REAL,
    kdj_hfq REAL,
    kdj_qfq REAL,
    kdj_d_bfq REAL,
    kdj_d_hfq REAL,
    kdj_d_qfq REAL,
    kdj_k_bfq REAL,
    kdj_k_hfq REAL,
    kdj_k_qfq REAL,
    ktn_down_bfq REAL,
    ktn_down_hfq REAL,
    ktn_down_qfq REAL,
    ktn_mid_bfq REAL,
    ktn_mid_hfq REAL,
    ktn_mid_qfq REAL,
    ktn_upper_bfq REAL,
    ktn_upper_hfq REAL,
    ktn_upper_qfq REAL,
    lowdays_bfq REAL,
    lowdays_hfq REAL,
    lowdays_qfq REAL,
    topdays_bfq REAL,
    topdays_hfq REAL,
    topdays_qfq REAL,
    macd_bfq REAL,
    macd_hfq REAL,
    macd_qfq REAL,
    macd_dea_bfq REAL,
    macd_dea_hfq REAL,
    macd_dea_qfq REAL,
    macd_dif_bfq REAL,
    macd_dif_hfq REAL,
    macd_dif_qfq REAL,
    mass_bfq REAL,
    mass_hfq REAL,
    mass_qfq REAL,
    ma_mass_bfq REAL,
    ma_mass_hfq REAL,
    ma_mass_qfq REAL,
    mfi_bfq REAL,
    mfi_hfq REAL,
    mfi_qfq REAL,
    mtm_bfq REAL,
    mtm_hfq REAL,
    mtm_qfq REAL,
    mtmma_bfq REAL,
    mtmma_hfq REAL,
    mtmma_qfq REAL,
    obv_bfq REAL,
    obv_hfq REAL,
    obv_qfq REAL,
    psy_bfq REAL,
    psy_hfq REAL,
    psy_qfq REAL,
    psyma_bfq REAL,
    psyma_hfq REAL,
    psyma_qfq REAL,
    roc_bfq REAL,
    roc_hfq REAL,
    roc_qfq REAL,
    maroc_bfq REAL,
    maroc_hfq REAL,
    maroc_qfq REAL,
    taq_down_bfq REAL,
    taq_down_hfq REAL,
    taq_down_qfq REAL,
    taq_mid_bfq REAL,
    taq_mid_hfq REAL,
    taq_mid_qfq REAL,
    taq_up_bfq REAL,
    taq_up_hfq REAL,
    taq_up_qfq REAL,
    trix_bfq REAL,
    trix_hfq REAL,
    trix_qfq REAL,
    trma_bfq REAL,
    trma_hfq REAL,
    trma_qfq REAL,
    vr_bfq REAL,
    vr_hfq REAL,
    vr_qfq REAL,
    wr_bfq REAL,
    wr_hfq REAL,
    wr_qfq REAL,
    wr1_bfq REAL,
    wr1_hfq REAL,
    wr1_qfq REAL,
    xsii_td1_bfq REAL,
    xsii_td1_hfq REAL,
    xsii_td1_qfq REAL,
    xsii_td2_bfq REAL,
    xsii_td2_hfq REAL,
    xsii_td2_qfq REAL,
    xsii_td3_bfq REAL,
    xsii_td3_hfq REAL,
    xsii_td3_qfq REAL,
    xsii_td4_bfq REAL,
    xsii_td4_hfq REAL,
    xsii_td4_qfq REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 备用行情
CREATE TABLE IF NOT EXISTS "bak_daily" (
    ts_code TEXT,
    trade_date TEXT,
    name TEXT,
    pct_change REAL,
    close REAL,
    change REAL,
    open REAL,
    high REAL,
    low REAL,
    pre_close REAL,
    vol_ratio REAL,
    turn_over REAL,
    swing REAL,
    vol REAL,
    amount REAL,
    selling REAL,
    buying REAL,
    total_share REAL,
    float_share REAL,
    pe REAL,
    industry TEXT,
    area TEXT,
    float_mv REAL,
    total_mv REAL,
    avg_price REAL,
    strength REAL,
    activity REAL,
    avg_turnover REAL,
    attack REAL,
    interval_3 REAL,
    interval_6 REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 每日涨跌停价格
CREATE TABLE IF NOT EXISTS "stk_limit" (
    trade_date TEXT,
    ts_code TEXT,
    pre_close REAL,
    up_limit REAL,
    down_limit REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 分红送股数据
CREATE TABLE IF NOT EXISTS "dividend" (
    ts_code TEXT,
    end_date TEXT,
    ann_date TEXT,
    div_proc TEXT,
    stk_div REAL,
    stk_bo_rate REAL,
    stk_co_rate REAL,
    cash_div REAL,
    cash_div_tax REAL,
    record_date TEXT,
    ex_date TEXT,
    pay_date TEXT,
    div_listdate TEXT,
    imp_ann_date TEXT,
    base_date TEXT,
    base_share REAL,
    PRIMARY KEY (ts_code, ann_date)
);

-- 沪深港通资金流向
CREATE TABLE IF NOT EXISTS "moneyflow_hsgt" (
    trade_date TEXT,
    ggt_ss REAL,
    ggt_sz REAL,
    hgt REAL,
    sgt REAL,
    north_money REAL,
    south_money REAL,
    PRIMARY KEY (trade_date)
);

-- 个股资金流向
CREATE TABLE IF NOT EXISTS "moneyflow" (
    ts_code TEXT,
    trade_date TEXT,
    buy_sm_vol INTEGER,
    buy_sm_amount REAL,
    sell_sm_vol INTEGER,
    sell_sm_amount REAL,
    buy_md_vol INTEGER,
    buy_md_amount REAL,
    sell_md_vol INTEGER,
    sell_md_amount REAL,
    buy_lg_vol INTEGER,
    buy_lg_amount REAL,
    sell_lg_vol INTEGER,
    sell_lg_amount REAL,
    buy_elg_vol INTEGER,
    buy_elg_amount REAL,
    sell_elg_vol INTEGER,
    sell_elg_amount REAL,
    net_mf_vol INTEGER,
    net_mf_amount REAL,
    PRIMARY KEY (ts_code, trade_date)
);

-- 个股资金流向(DC)
CREATE TABLE IF NOT EXISTS "moneyflow_dc" (
    trade_date TEXT,
    ts_code TEXT,
    name TEXT,
    pct_change REAL,
    close REAL,
    net_amount REAL,
    net_amount_rate REAL,
    buy_elg_amount REAL,
    buy_elg_amount_rate REAL,
    buy_lg_amount REAL,
    buy_lg_amount_rate REAL,
    buy_md_amount REAL,
    buy_md_amount_rate REAL,
    buy_sm_amount REAL,
    buy_sm_amount_rate REAL,
    PRIMARY KEY (ts_code, trade_date)
);
